In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

Output is: 


In [9]:
print("Output is: ")
print("One Dimensional Array is :",a)

Output is: 
One Dimensional Array is : [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
b = np.array([[10,20],[30,40]])
print("Two Dimensional Array is \n:",b)

Two Dimensional Array is 
: [[10 20]
 [30 40]]


In [13]:
c = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Three Dimensional Array is: \n",c)

Three Dimensional Array is: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [16]:
# array indexing and numpy attributes
x1 = np.array([56,23,55,64])
x2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array indexing and numpy attributes")
print(x1)
print("x2 ndim:",x2.ndim)
print("x2 shape:",x2.shape)
print("x2 size:",x2.size)

Array indexing and numpy attributes
[56 23 55 64]
x2 ndim: 2
x2 shape: (3, 3)
x2 size: 9


In [17]:
# accessing single elements

print("Accessing single elements")
print(x1[-2])
print(x2)
x2[1,2]=60
print(x2)

Accessing single elements
55
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]


In [20]:
# array slicing
print("Array slicing")
x = np.arange(10)
print(x[5:9])
print(x[:5])
print(x[1::3])
print(x2)
print(x2[0:2,0:2])

Array slicing
[5 6 7 8]
[0 1 2 3 4]
[1 4 7]
[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]
[[1 2]
 [4 5]]


In [22]:
# concatenation of array
print("Concation of array")
p = np.array([1,2,3])
q = np.array([8,12,14])
print(np.concatenate([p,q]))

Concation of array
[ 1  2  3  8 12 14]


In [25]:
# splitting of array
y = [1,2,3,99,99,3,2,1]
d,e = np.split(x,[2])
print(d,e)

[0 1] [2 3 4 5 6 7 8 9]


In [26]:
# Functions
print("Functions:")
print("add")
t = np.array([1,2,3])
print("add")
print(np.add(t,2))
print("Subtract")
print(np.subtract(t,2))
print("negative")
print(np.negative(t))
print("Multiply")
print(np.multiply(t,2))
print("Divide")
print(np.divide(t,5))
print("Floor divide")
print(np.floor_divide(t,2))
print("power")
print(np.power(t,2))
print("modulus")
print(np.mod(t,2))

Functions:
add
add
[3 4 5]
Subtract
[-1  0  1]
negative
[-1 -2 -3]
Multiply
[2 4 6]
Divide
[0.2 0.4 0.6]
Floor divide
[0 1 1]
power
[1 4 9]
modulus
[1 0 1]


In [27]:
# absolute
print("Absolute")
print(np.abs([-2,-1,0,1,2]))

Absolute
[2 1 0 1 2]


In [28]:
# Trigonometric
print("trigonometric")
theta = [0,1.57,3.14]
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

trigonometric
[0.         0.99999968 0.00159265]
[ 1.00000000e+00  7.96326711e-04 -9.99998732e-01]
[ 0.00000000e+00  1.25576559e+03 -1.59265494e-03]


In [29]:
# Exponent
print("Exponent")
print(np.exp(x))
print(np.exp2(x))
print(np.power(x,3))

Exponent
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[  0   1   8  27  64 125 216 343 512 729]


In [32]:
print("Log")
print(np.log(10))
print(np.log2(10))
print(np.log10(1))

Log
2.302585092994046
3.321928094887362
0.0
